name: cylinder_management
description: A comprehensive Cylinder Management System for tracking industrial gas cylinders

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

# Version information
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State management
  flutter_riverpod: ^2.3.6
  
  # API & Network
  dio: ^5.1.2
  connectivity_plus: ^4.0.1
  
  # Local storage
  shared_preferences: ^2.1.1
  
  # UI components
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.5
  intl: ^0.18.1
  google_fonts: ^4.0.4
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.0
  flutter_slidable: ^3.0.0
  
  # QR code scanner
  mobile_scanner: ^3.2.0
  qr_flutter: ^4.1.0
  
  # Charts and reports
  fl_chart: ^0.62.0
  syncfusion_flutter_charts: ^22.1.34
  printing: ^5.10.4
  pdf: ^3.10.1
  
  # Forms and validation
  form_field_validator: ^1.1.0
  
  # Utilities
  uuid: ^3.0.7
  url_launcher: ^6.1.11
  image_picker: ^0.8.7+5
  path_provider: ^2.0.15
  permission_handler: ^10.2.0
  device_info_plus: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# Flutter configuration
flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
